# Generated by Django 4.1.3 on 2022-11-18 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Admin_username', models.CharField(blank=True, max_length=50, null=True)),
                ('Admin_password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeUserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(blank=True, default='', max_length=100)),
                ('Employee_Number', models.CharField(blank=True, default='', max_length=30)),
                ('Employee_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Employee_Department', models.CharField(blank=True, default='', max_length=100)),
                ('Employee_Designation', models.CharField(blank=True, default='', max_length=100)),
                ('fk_Admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Faceattendence_App.adminusermaster')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Check_In_Out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Id', models.CharField(blank=True, default='', max_length=100)),
                ('Attendance_Type', models.CharField(blank=True, default='', max_length=100)),
                ('IP_Address', models.CharField(blank=True, default='', max_length=100)),
                ('check_In_out_Created_date_time', models.DateTimeField(blank=True, null=True)),
                ('fk_Employee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Faceattendence_App.employeeusermaster')),
            ],
        ),
    ]
