# Generated by Django 4.1.3 on 2022-11-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faceattendence_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_check_in_out',
            old_name='check_In_out_Created_date_time',
            new_name='check_In_Created_date_time',
        ),
        migrations.RemoveField(
            model_name='employee_check_in_out',
            name='Employee_Id',
        ),
        migrations.AddField(
            model_name='employee_check_in_out',
            name='check_out_Created_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
