# Generated by Django 4.1.3 on 2022-11-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faceattendence_App', '0002_rename_check_in_out_created_date_time_employee_check_in_out_check_in_created_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='dummy_image/')),
            ],
        ),
    ]
