# Generated by Django 4.1.3 on 2022-11-23 05:43

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Faceattendence_App', '0003_dummy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=250, null=True)),
                ('pickle_obj', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
